### ISSUE TITLE
After creating a space clicking see details doesn't work

### ISSUE THREAD

**Issue by tiusty** [patnorris/PWS#8]
When you click create space, if you click view details on that space afterwards, it won't load the details. You need to refresh the page for it to show the details
<img width="600" alt="image" src="https://user-images.githubusercontent.com/10234268/222034534-8353d080-74ed-421d-ac5c-37d5e9e733a7.png">

The bottom space which I just created, won't let me click see details

**Comment by patnorris** [comment]
nice catch, this commit fixes the issue: https://github.com/patnorris/PWS/pull/7/commits/3212e3e2b7e2b12e8146123dae00fd0bfde569c4
